package com.ainovel;

import org.mybatis.spring.annotation.MapperScan;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.context.properties.ConfigurationPropertiesScan;
import org.springframework.cache.annotation.EnableCaching;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@EnableCaching
@ConfigurationPropertiesScan
@MapperScan(basePackages = {
        "com.ainovel.user.mapper",
        "com.ainovel.novel.mapper",
        "com.ainovel.community.mapper",
        "com.ainovel.reading.mapper",
        "com.ainovel.audit.mapper"
})
public class AInovelApplication {

    public static void main(String[] args) {
        SpringApplication.run(AInovelApplication.class, args);
    }

}
