package com.ainovel;

// [警告] 缺少必需的类路径条目。请检查项目依赖和构建配置（如pom.xml或build.gradle），确保所有必需依赖已正确添加。

import org.mybatis.spring.annotation.MapperScan;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.context.properties.ConfigurationPropertiesScan;
import org.springframework.cache.annotation.EnableCaching;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@EnableCaching
@ConfigurationPropertiesScan
@MapperScan(basePackages = {
        "com.ainovel.admin.mapper",
        "com.ainovel.user.mapper",
        "com.ainovel.novel.mapper",
        "com.ainovel.community.mapper",
        "com.ainovel.reading.mapper",
        "com.ainovel.audit.mapper"
})
public class AInovelApplication {

    public static void main(String[] args) {
        SpringApplication.run(AInovelApplication.class, args);
    }

}
