CREATE TABLE IF NOT EXISTS user_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'NORMAL',
    roles VARCHAR(255) NOT NULL DEFAULT 'USER',
    login_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_user_account_username ON user_account (username);
CREATE INDEX IF NOT EXISTS idx_user_account_status ON user_account (status);

CREATE TABLE IF NOT EXISTS user_profile (
    user_id BIGINT NOT NULL PRIMARY KEY,
    nickname VARCHAR(64) NOT NULL,
    avatar_url VARCHAR(512),
    bio VARCHAR(1000),
    level INT NOT NULL DEFAULT 1,
    verified_status VARCHAR(32) NOT NULL DEFAULT 'UNVERIFIED',
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_profile_account FOREIGN KEY (user_id) REFERENCES user_account (id)
);

CREATE TABLE IF NOT EXISTS user_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    to_user_id BIGINT NOT NULL,
    type VARCHAR(32) NOT NULL,
    title VARCHAR(200) NOT NULL,
    content CLOB NOT NULL,
    biz_type VARCHAR(64),
    biz_id BIGINT,
    producer VARCHAR(64),
    trace_id VARCHAR(64),
    read_at TIMESTAMP(3),
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_user_message_inbox ON user_message (to_user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_user_message_unread ON user_message (to_user_id, read_at);

CREATE TABLE IF NOT EXISTS novel (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    intro CLOB,
    cover_url VARCHAR(512),
    category_id BIGINT,
    tag_ids VARCHAR(255),
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    latest_chapter_id BIGINT,
    word_count BIGINT NOT NULL DEFAULT 0,
    audit_task_id VARCHAR(64),
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_novel_author_status ON novel (author_id, status);
CREATE INDEX IF NOT EXISTS idx_novel_updated_at ON novel (updated_at);

CREATE TABLE IF NOT EXISTS novel_chapter (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    novel_id BIGINT NOT NULL,
    chapter_no INT NOT NULL,
    title VARCHAR(200) NOT NULL,
    content CLOB NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    audit_task_id VARCHAR(64),
    published_at TIMESTAMP(3),
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_novel_chapter_novel FOREIGN KEY (novel_id) REFERENCES novel (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_novel_chapter_no ON novel_chapter (novel_id, chapter_no);
CREATE INDEX IF NOT EXISTS idx_novel_chapter_query ON novel_chapter (novel_id, status, chapter_no);

CREATE TABLE IF NOT EXISTS comment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type VARCHAR(32) NOT NULL,
    target_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    parent_id BIGINT,
    reply_to_user_id BIGINT,
    content CLOB NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'VISIBLE',
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_comment_target_page ON comment (target_type, target_id, status, created_at);
CREATE INDEX IF NOT EXISTS idx_comment_user_created ON comment (user_id, created_at);

CREATE TABLE IF NOT EXISTS reaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reaction_type VARCHAR(32) NOT NULL,
    target_type VARCHAR(32) NOT NULL,
    target_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_reaction_user_target
    ON reaction (user_id, reaction_type, target_type, target_id);
CREATE INDEX IF NOT EXISTS idx_reaction_target_counter
    ON reaction (reaction_type, target_type, target_id, status);

CREATE TABLE IF NOT EXISTS user_follow (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    target_user_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_user_follow_pair ON user_follow (user_id, target_user_id);
CREATE INDEX IF NOT EXISTS idx_user_follow_target ON user_follow (target_user_id, status, updated_at);

CREATE TABLE IF NOT EXISTS audit_task (
    task_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    biz_type VARCHAR(64) NOT NULL,
    biz_id BIGINT NOT NULL,
    content_snapshot CLOB NOT NULL,
    content_hash VARCHAR(128) NOT NULL,
    audit_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    risk_level VARCHAR(32),
    reason_code VARCHAR(64),
    reason_text VARCHAR(1024),
    reviewer_id BIGINT,
    retry_count INT NOT NULL DEFAULT 0,
    rule_version VARCHAR(32),
    reviewed_at TIMESTAMP(3),
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_audit_task_hash ON audit_task (biz_type, biz_id, content_hash);
CREATE INDEX IF NOT EXISTS idx_audit_task_status ON audit_task (audit_status, created_at);

CREATE TABLE IF NOT EXISTS reading_progress (
    user_id BIGINT NOT NULL,
    novel_id BIGINT NOT NULL,
    chapter_id BIGINT NOT NULL,
    progress_percent INT NOT NULL DEFAULT 0,
    page_offset BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, novel_id)
);

CREATE INDEX IF NOT EXISTS idx_reading_progress_novel ON reading_progress (novel_id, updated_at);
