CREATE TABLE IF NOT EXISTS bookmark (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    novel_id BIGINT NOT NULL,
    chapter_id BIGINT NOT NULL,
    page_offset BIGINT NOT NULL DEFAULT 0,
    note VARCHAR(500),
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_bookmark_user_chapter ON bookmark (user_id, chapter_id);
CREATE INDEX IF NOT EXISTS idx_bookmark_user_novel ON bookmark (user_id, novel_id);

CREATE TABLE IF NOT EXISTS reading_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    novel_id BIGINT NOT NULL,
    chapter_id BIGINT NOT NULL,
    last_read_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_reading_history_user_novel ON reading_history (user_id, novel_id);
CREATE INDEX IF NOT EXISTS idx_reading_history_user_time ON reading_history (user_id, last_read_at);
