ALTER TABLE novel
    ADD COLUMN publisher_name VARCHAR(128) DEFAULT '平台收录' NOT NULL;

CREATE TABLE IF NOT EXISTS novel_community_partition (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    novel_id BIGINT NOT NULL,
    partition_key VARCHAR(32) NOT NULL,
    partition_name VARCHAR(64) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_novel_partition_novel FOREIGN KEY (novel_id) REFERENCES novel (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_novel_partition_key
    ON novel_community_partition (novel_id, partition_key);
CREATE INDEX IF NOT EXISTS idx_novel_partition_query
    ON novel_community_partition (novel_id, status, sort_order, id);

INSERT INTO novel_community_partition (novel_id, partition_key, partition_name, sort_order, status)
SELECT n.id, 'GENERAL', '综合讨论', 10, 'ACTIVE'
FROM novel n
WHERE NOT EXISTS (
    SELECT 1 FROM novel_community_partition p WHERE p.novel_id = n.id AND p.partition_key = 'GENERAL'
);

INSERT INTO novel_community_partition (novel_id, partition_key, partition_name, sort_order, status)
SELECT n.id, 'PLOT', '剧情讨论', 20, 'ACTIVE'
FROM novel n
WHERE NOT EXISTS (
    SELECT 1 FROM novel_community_partition p WHERE p.novel_id = n.id AND p.partition_key = 'PLOT'
);

INSERT INTO novel_community_partition (novel_id, partition_key, partition_name, sort_order, status)
SELECT n.id, 'CHARACTER', '人物讨论', 30, 'ACTIVE'
FROM novel n
WHERE NOT EXISTS (
    SELECT 1 FROM novel_community_partition p WHERE p.novel_id = n.id AND p.partition_key = 'CHARACTER'
);
