CREATE TABLE IF NOT EXISTS admin_operation_log (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(64) NOT NULL,
    biz_type VARCHAR(64) NOT NULL,
    biz_id BIGINT NOT NULL,
    operator_id BIGINT,
    operator_roles VARCHAR(128),
    from_status VARCHAR(64),
    to_status VARCHAR(64),
    reason VARCHAR(1024),
    trace_id VARCHAR(64),
    request_path VARCHAR(255),
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_admin_operation_log_created
    ON admin_operation_log (created_at, log_id);
CREATE INDEX IF NOT EXISTS idx_admin_operation_log_action
    ON admin_operation_log (action, created_at);
CREATE INDEX IF NOT EXISTS idx_admin_operation_log_biz
    ON admin_operation_log (biz_type, biz_id, created_at);
CREATE INDEX IF NOT EXISTS idx_admin_operation_log_operator
    ON admin_operation_log (operator_id, created_at);
